{{- if .Values.emqxLicneseSecretName  }}
apiVersion: v1
kind: Secret
metadata:
  name: emqx-lik-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx.lic: {{ .Values.emqxLicneseSecretName | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxAclConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: emqx-acl-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  acl.conf: {{ .Values.emqxAclConfig | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxAuthConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: emqx-auth-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx_auth_username.conf: {{ .Values.emqxAuthConfig | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxPluginConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: emqx-plugin-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  loaded_plugins: {{ .Values.emqxPluginConfig | b64enc | quote }}
{{- end}}
