apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- toYaml .Values.emqxConfig | nindent 2 }}
