{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dashboard
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}-ingress
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.domainname }}
  - host: {{ printf "%s.%s" .Release.Name .Values.ingress.domainname }}
    http:
      paths:
      - path: /
        backend:
          serviceName:  {{ .Release.Name }}
          servicePort: {{ .Values.emqxConfig.EMQX_DASHBOARD__LISTENER__HTTP | default 18083 }}
  {{- end }}
  {{- range .Values.ingress.alias }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          serviceName:  {{ template "Release.Name" $ }}
          servicePort: {{ .Values.ingress.aliasports }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
