{{- if .Values.emqxLicneseSecretName  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lik-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx.lic: {{ .Values.emqxLicneseSecretName | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxAclConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-acl-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  acl.conf: {{ .Values.emqxAclConfig | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxAuthConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx_auth_username.conf: {{ .Values.emqxAuthConfig | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxStatsdConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-statsd-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx_statd.conf: {{ .Values.emqxStatsdConfig | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxPluginConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plugin-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  loaded_plugins: {{ .Values.emqxPluginConfig | b64enc | quote }}
{{- end}}
