---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-exporter-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  admin_password: "cHVibGljCg=="

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-exporter-auth-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  auth.json: "ewogICJ1c2VybmFtZSI6ICJhZG1pbiIsCiAgInBhc3N3b3JkIjogInB1YmxpYyIKfQo="

---
{{- if .Values.emqxLicneseSecretName  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lik-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx.lic: {{ .Values.emqxLicneseSecretName | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxAclConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-acl-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  acl.conf: {{ .Values.emqxAclConfig | b64enc | quote }}
{{- end}}

---
{{- if .Values.emqxAuthConfig  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-instance
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  emqx_auth_username.conf: {{ .Values.emqxAuthConfig | b64enc | quote }}
{{- end}}
