apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: {{ .Release.Name }}
  {{- if eq .Values.service.type "LoadBalancer" }}
    cloud.google.com/load-balancer-type: Internal
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if eq .Values.service.type "LoadBalancer" }}
    app.kubernetes.io/name: {{ .Release.Name }}
  {{- else }}
    app.kubernetes.io/name: {{ .Release.Name }}-ingress
  {{- end}}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mqtt
    port: {{ .Values.emqxConfig.EMQX_LISTENER__TCP__EXTERNAL | default 1883 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__TCP__EXTERNAL | default 1883 }}
  - name: mqttssl
    port: {{ .Values.emqxConfig.EMQX_LISTENER__SSL__EXTERNAL | default 8883 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__SSL__EXTERNAL | default 8883 }}
  - name: mgmt
    port: {{ .Values.emqxConfig.EMQX_MANAGEMENT__LISTENER__HTTP | default 8081 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_MANAGEMENT__LISTENER__HTTP | default 8081 }}
  - name: websocket
    port: {{ .Values.emqxConfig.EMQX_LISTENER__WS__EXTERNAL | default 8083 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__WS__EXTERNAL | default 8083 }}
  - name: wss
    port: {{ .Values.emqxConfig.EMQX_LISTENER__WSS__EXTERNAL | default 8084 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__WSS__EXTERNAL | default 8084 }}
{{- if eq .Values.service.type "ClusterIP" }}
  - name: dashboard
    port: 80
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_DASHBOARD__LISTENER__HTTP | default 18083 }}
{{- end}}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
{{- if eq .Values.service.type "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: {{ .Release.Name }}-dashboard
    cloud.google.com/load-balancer-type: Internal
  name: {{ .Release.Name }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ingress
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Release.Name }}-dashboard
    port: 80
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_DASHBOARD__LISTENER__HTTP | default 18083 }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: {{ .Release.Name }}-headless
  name: {{ .Release.Name }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  ports:
  - name: mqtt
    port: {{ .Values.emqxConfig.EMQX_LISTENER__TCP__EXTERNAL | default 1883 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__TCP__EXTERNAL | default 1883 }}
  - name: mqttssl
    port: {{ .Values.emqxConfig.EMQX_LISTENER__SSL__EXTERNAL | default 8883 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__SSL__EXTERNAL | default 8883 }}
  - name: mgmt
    port: {{ .Values.emqxConfig.EMQX_MANAGEMENT__LISTENER__HTTP | default 8081 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_MANAGEMENT__LISTENER__HTTP | default 8081 }}
  - name: websocket
    port: {{ .Values.emqxConfig.EMQX_LISTENER__WS__EXTERNAL | default 8083 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__WS__EXTERNAL | default 8083 }}
  - name: wss
    port: {{ .Values.emqxConfig.EMQX_LISTENER__WSS__EXTERNAL | default 8084 }}
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_LISTENER__WSS__EXTERNAL | default 8084 }}
  - name: dashboard
    port: 80
    protocol: TCP
    targetPort: {{ .Values.emqxConfig.EMQX_DASHBOARD__LISTENER__HTTP | default 18083 }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
